name: puroanalysis
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - conda-forge::jupyterlab
  - pytorch::pytorch
  - pytorch::torchvision
  - matplotlib
  - pandas
  - conda-forge::scikit-image
  - conda-forge::seaborn
  - conda-forge::dask
  - conda-forge::dask-jobqueue
  - pyyaml
  - pip:
      - nd2
      - cellpose
